# Generated by Django 5.2.9 on 2025-12-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_ai_summary_article_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
