# Generated by Django 5.2.9 on 2025-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='date',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
