# Generated by Django 5.2.9 on 2025-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsitem_ai_summary_newsitem_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
