# Generated by Django 5.2.9 on 2025-12-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_newsitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='content_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='reading_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='summary_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='risk_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
