# Generated by Django 5.2.9 on 2025-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newsitem_content_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
